---
title: "Bending Moment Roughness"
author: "Locatelli, T. Hale, S. Nicoll, B. Gardiner, B."
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Bending Moment Roughness}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
The roughness method in ForestGALES^[Throughout the package documentation, we will use the name *ForestGALES* to refer to the model characteristics as described in e.g. Hale et al. (2015) or Gardiner et al. (2000, 2008). Conversely, when we refer to the functionalities implemented in this package, we use the name *fgr*] is based on the the drag per unit area imposed on the canopy surface by the wind. The wind's shear stress ($\tau$ (N m-2) on the canopy surface is calculated as:

$\tau = - \rho u_{*}^2\tag{Eq.1}$

where $\rho$ (kg m^-3) is the air density and $u_*$ is the friction velocity. The shear stress is the drag per unit area imposed on the canopy surface
by the wind. If we call average square spacing between trees D (m), then $\tau D^2$ is the average drag or force on each tree. Thom (1971) showed that this force can be regarded as acting at the height of the zero-plane displacement (d). Gardiner et al. (2000) and Quine and Gardiner (2007) showed that the average drag on a tree in a stand of density *D* at any height (z) on the stem below d ($(d-z)\tau D^2$) allows calculating the applied mean bending moment (N m) with: 

$M_{appl\_mean}(z) = (d -z)\rho u_*^2D^2\tag{Eq.2}$ 


By assuming a logarithmic wind profile above the canopy, the turning moment on a tree at height *z* above the ground can be calculated in terms of the canopy top wind speed ($u_h$, m s-1):

$M_{appl\_mean}(z) = (d -z)\rho \biggl(\frac{Du_hk}{ln\frac{h-d}{z_0}}\biggr)^2\tag{Eq.3}$

where h is the average tree height (m), z0 is the aerodynamic roughness (m), and k = 0.4 (von Karman constant). Wind damage on trees however is caused by "extreme" winds that exceed the mean wind speed. Therefore, $M_{appl\_mean}$ can then be converted into a calculation of the maximum turning moment by multiplying by a factor that accounts for the effects of edge, gap, and gustiness (`edge_gap_gust_factor`, G):

$M_{appl\_max}(z) = (d -z)\rho G\biggl(\frac{Du_hk}{ln\frac{h-d}{z_0}}\biggr)^2\tag{Eq.4}$

Incorporating gustiness in the `edge_gap_gust_factor` is required because whilst the maximum wind loading occurs during short-term gusts of a few seconds, the maximum wind loading needs to be predicted from the mean hourly wind speed ($u_h$) in order to match with standard climatological wind data which is usually reported as mean hourly values. G is the ratio between maximum and mean turning moment (Gardiner et al., 2000) and is calculated as a function of the spacing to tree height ratio, based on wind tunnel measurements (Gardiner et al., 1997).

In Eq. 4 the additional moment provided by the overhanging displaced mass of the canopy, of the stem, and of snow (when present) is not accounted for yet. This is done with the introduction of the Deflection Loading Factor (DLF), calculated with the `DLF_calc` function in the *fgr* R package. 

## The *fgr* R package `BM_rou` function

The `BM_rou` function calculates the maximum applied bending moment ($M_{appl\_max}$) at tree base:  

$M_{appl\_max}(tree\_base) = d\rho G\biggl(\frac{Du_hk}{ln\frac{h-d}{z_0}}\biggr)^2\tag{Eq.5}$^[notice that the bending moment is calculated at tree base (therefore z in Eq. 2 to 5 is 0)]

The additional moment provided by the weight of the stem, canopy, and snow (when present) is accounted for with DLF in the calculation of the critical wind speeds (see the `Critical Wind Speeds` documentation). DLF effectively incorporates the applied and additional turning moments in a single term. In the *fgr* R package, the $M_{appl\_max}$ calculated with the `BM_rou` function is only used to compute DLF. However, because of the form of the `deflection_fun` function, and of the mathematical form used in the `DLF_calc` function (a Maclaurin series), the calculation of DLF is effectively independent of the bending moment generated by the wind, while it is completely dependent on the size and form of the tree and the canopy. Therefore, the calculation of the $M_{appl\_max}$ with the `BM_rou` function is only kept for completeness.

## Max bending moment formula in the calculation of the Critical Wind Speeds in the *fgr* R package 

While Eq. 5 is written in terms of the mean hourly wind speed $u_h$, it is possible to convert the mean applied turning moment calculated in Eq.2 to $M_{appl\_max}$ in the same way it was done for Eq. 3, by adding the influence of G, the *edge_gap_gust_factor*. This therefore yields:

$M_{appl\_max}(tree\_base) = d\rho G\cdot u_*^2D^2\tag{Eq.6}$

Eq.6 employs $u_*$ rather than $u_h$ as used in Eq.3 to 5. This makes the computation of $M_{appl\_max}$ much more straightforward than for Eq. 5. Converting $u_*$ to $u_h$ is then possible by employing $\gamma$, "*the frontal area of the roughness elements, from the mean wind direction, per unit ground area*" (Raupach, 1994), with the use of the `gammasolved_fun` function (see the `Streamlining and Drag` documentation). This approach is used in the *fgr* R package to calculate the critical wind speeds for breakage and overturning.


## Bibliography
- Gardiner, B.A., Stacey, G.R., Belcher, R.E., Wood, C.J. 1997. Field and wind tunnel assessments of the implications of respacing and thinning for tree stability. Forestry, 70, 233-252.
- Gardiner, B.A., Peltola, H.M., Kellomaki, S. 2000. Comparison of two models for predicting the critical wind speeds required to damage coniferous trees. Ecological Modelling, 129, 1-23.
- Quine CP and Gardiner BA, 2007. Understanding how the interaction of wind and trees results in windthrow, stem breakage and canopy gap formation. In: Johnson E (Ed.), Plant Disturbance Ecology: The Process and the Response. Academic Press, Burlington, USA, pp. 103 - 155.
- Raupach, M.R., 1992. Drag and drag partition on rough surfaces. Boundary Layer Meteorol. 60, 375–395.
- Raupach, M.R. 1994 Simplified Expressions for vegetation roughness and zero-plane displacement as functions of canopy height and area index.Boundary-Layer Meteorology, 71, 211-216.
- Thom AS, 1971. Momentum absorption by vegetation. Q J Roy Met Soc 97, 414-428.
