---
title: "Streamlining and drag on forest canopies"
author: "Locatelli, T. Hale, S. Nicoll, B. Gardiner, B."
date: "`r Sys.Date()`"
output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{Streamlining and Drag}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
To calculate the wind loading on a tree, ForestGALES^[Throughout the package documentation, we will use the name *ForestGALES* to refer to the model characteristics as described in e.g. Hale et al. (2015) or Gardiner et al. (2000, 2008). Conversely, when we refer to the functionalities implemented in this package, we use the name *fgr*] adopts an empirical approach derived from Mayhead et al. (1975). With this method, the measured drag of trees defines the relationship between the drag of the air on a surface and the aerodynamic roughness of the surface (e.g. forest canopy).

## Drag over canopies

The wind speed (u) over a forest canopy is given by a logarithmic profile of the form:
\begin{align}
u_{(z)}= \frac {u_*}{k} ln\Biggl(\frac{z-d}{z_0}\Biggr)
\end{align}
where z (m) is height above the surface, $u_*$ (m s^-1) is the friction velocity, $k$ is von Karman’s constant (0.4), $d$ (m) is the zero-plane displacement and $z_0$ (m) is the aerodynamic roughness. The friction velocity ($u_*$) is defined by:
\begin{align}
\tau = - \rho \cdot u_{*}^2
\end{align}
where $\tau$ (N m^-2) is the shear stress on the surface and $\rho$ (kg m^-3) is the air density. The shear stress is the drag per unit area imposed on the canopy surface by the wind. 
If we call the average square spacing between trees D (m), then $\tau D^2$ is the average drag or force on each tree. Thom (1971) showed that this force can be regarded as acting at the height of the zero-plane displacement. As a consequence, the mean bending moment (N m) at any height (z) on the stem below $d$ is given by:
\begin{align}
(d-z)\tau D^2
\end{align}
The aerodynamic roughness and the zero plane displacement are derived from  tree height (h), tree square spacing, canopy depth ($Crown_d$, m) and canopy breadth ($Crown_b$, m) using the method of Raupach (1992). The idealised shape of the tree is that of a cylinder with the height (h) of the tree and width (b, m) given by the frontal area of the streamlined crown (A, m^2) distributed evenly over the depth of the tree ($b = A/h$). In the *fgr* R package the `lambdacapital_fun` function calculates $\Lambda$, the frontal area of the streamlined canopy per ground area (defined by spacing). Effectively, $\Lambda$ is canopy drag per unit ground area (i.e. $2\lambda$ in Raupach (1992)). The `lambdacapital_fun` function makes use of the `canopy_breadth_fun` function to calculate the breadth of the streamlined canopy under wind loading. The frontal area is assumed to be diamond-shaped and is calculated as:
\begin{align}
A=\frac{C_dCrown_dCrown_b}{2}
\end{align}
The dimensionless drag coefficient ($C_d$) adjusts the frontal area to account for streamlining and is derived from power function fits to the experimental data of Mayhead (1973):
\begin{align}
C_d = C\cdot u^{-N}
\end{align}
where C is the value of the drag coefficient at rest, N is the exponent that describes the power fit to the data, and $u$ is the wind speed of interest (in m s-1). These canopy drag experiments have been replicated for different species by e.g. Vollsinger et al. (2005). The wind speed $u$ used in these experiments is typically between 10 and 25 m s^-1 for conifers, and between 10 and 20 m s^-1 for broadleaves. These limits are accounted for in the *fgr* R package in the modelling the crown streamlining of different species, as implemented in the package *Internal Data*.

## Aerodynamic roughness
The aerodynamic roughness ($z_0$) of a composite surface (such as the top of a forest stand) is related to the height of the roughness elements (i.e. the individual trees) and to the spacing between the elements (the square spacing in ForestGALES).^[A more analytical definition of $z_0$ is that it is the height above ground where a neutral (i.e. neither stable nor unstable) wind profile has zero wind speed] Raupach (1994) showed that $z_0$ is related to the ratio between wind speed at canopy top ($u_h$) and friction velocity, and to $\Psi_h$, the "roughness-sublayer influence funtion. The $\Psi_h$ function describes how the velocity profile immediately above the roughness elements departs from the inertial-sublayer logarithmic law:
\begin{align}
u_{(z)}= (u_*/k)\ ln(z/z_0)
\end{align}
which is a simplification of the logarithmic profile in Eq. 1 that is devoid of the effect of $d$). It is implemented in ForestGALES in the function `z0_fun`. The `gammasolved_fun` function calculates $\gamma$, "*the frontal area of the roughness elements, from the mean wind direction, per unit ground area*" (Raupach, 1994). This is calculated as the $\frac{u_h}{u_*}$ ratio, combining the original approach in Raupach (1992) and the simplification introduced in Raupach (1994). 

## Zero-plane displacement
As described by Thom (1971), $d$ is the height of the roughness elements where absorption of momentum is assumed to take place (aka the height of a "centre of pressure"). This assumption is based on the idea that the distribution of the shearing stress $\tau$ over the roughness elements is aerodynamically equivalent to the entire shear stress being applied at a height $d$. The zero-plane displacement is calculated in *fgr* R with the `zpd_fun` function which makes use of the simplified formula in Raupach (1994) that is applicable to roughness elements of very different vertical distribution of width (e.g. crown breadth as described above).


## Bibliography
* Mayhead, G.J. 1973. Some drag coefficients for British forest trees derived from wind tunnel studies. Agricultural Meteorology, 12, 123-130
* Mayhead, G.J., Gardiner, J.B.H., Durrant, D.W., 1975. Physical properties of conifers in relation to plantation stability. Forestry Commission, Edinburgh. Unpublished report.
* Raupach, M.R., 1992. Drag and drag partition on rough surfaces. Boundary Layer Meteorol. 60, 375–395.
* Raupach, M.R. 1994 Simplified Expressions for vegetation roughness and zero-plane displacement as functions of canopy height and area index.Boundary-Layer Meteorology, 71, 211-216.
* Thom, A.S., 1971. Momentum absorption by vegetation. Q. J. R. Meteorol. Soc. 97, 414–428.
* Vollsinger, S., Mitchell, S.J., Byrne, K.E., Novak, M.D., Rudnicki, M. 2005. Wind tunnel measurements of crown streamlining and drag relationships for several hardwood species. Canadian Journal of Forest Research-Revue Canadienne De Recherche Forestiere, 35, 1238-1249.
